button_card_templates: !include ui_templates/button_card_templates.yaml
decluttering_templates: !include ui_templates/mini_graph.yaml
kiosk_mode:
  user_settings:
    - users:
        - "Tablet"
      hide_header: true

views:
  - !include ui_views/mobile_lights.yaml
