- platform: smartir
  name: Study AC
  unique_id: study_ac
  device_code: 999
  controller_data: remote.study_remote_remote
  temperature_sensor: sensor.study_remote_temperature
  humidity_sensor: sensor.study_remote_humidity

- platform: smartir
  name: Bedroom AC
  unique_id: Bedroom_ac
  device_code: 999
  controller_data: remote.bedroom_remote_remote
  temperature_sensor: sensor.bedroom_remote_temperature
  humidity_sensor: sensor.bedroom_remote_humidity

- platform: smartir
  name: Kitchen AC
  unique_id: Kitchen_ac
  device_code: 1800
  controller_data: remote.kitchen_remote_remote
  temperature_sensor: sensor.kitchen_remote_temperature
  humidity_sensor: sensor.kitchen_remote_humidity
